### ISSUE TITLE
move bootstrap-editable-table to npm

### ISSUE THREAD

**Issue by zoepage** [gr2m/initials#10]
As far as we have bootstrap-editable-table as bower dependency atm, I'd like to remove it and load bootstrap-editable-table via npm. Is this possible atm @gr2m?

https://github.com/gr2m/bootstrap-editable-table

**Comment by gr2m** [comment]
yeah you add it as devDependency with the `.git` url

**Comment by zoepage** [comment]
Fixed with https://github.com/gr2m/initials/commit/68e6dcdc436d319948e6758dea94f43bd69af58e
