### ISSUE TITLE
move initials.js to spec folder

### ISSUE THREAD

**Issue by zoepage** [gr2m/initials#11]
@gr2m 
Is it possible to move the initials.js to a specs folder or would it break something?
I'd love to add a cleaned up structure for all the modules.

**Comment by zoepage** [comment]
We'd say, we postpone the task after refactoring all the modules. 
Just to be sure, the folder structure fits everywhere.

**Comment by gr2m** [comment]
I think one test file is enough for the lib, and I don't think we need any integration tests, so I'd say let's keep it simple and stick with the `test/initials-test.js`. Okay with you?

**Comment by zoepage** [comment]
Yes, totally ok with it :)
