### ISSUE TITLE
same initials for different names

### ISSUE THREAD

**Issue by zoepage** [gr2m/initials#12]
For different names same initials appear. We need not just compare the Strings, but also the length of the name.

// scheme
`['Moe Minutes', 'Moe Min'] -> ['MMi', 'MMi']`

// test
````
  t.deepEqual(initials(['Moe Minutes', 'Moe Min'], 3), ['MMi', 'MMi'], 'not same name')
  t.deepEqual(initials(['Moe Minutes', 'Moe Mina'], 3), ['MMi', 'MoM'], 'not same name')

````

Start: `function initialsForMultipleNames (names, options)`

**Comment by zoepage** [comment]
@gr2m could you verify this or is this "a feature"? :)

**Comment by gr2m** [comment]
Good catch! Yes, this is a bug! 

```js
initials([['Moe Minutes', 'Moe Min'])
// returns ["MMi", "MMi"]
// should return sth like ["MoM", "MMi"]
```

I think this is rather an edge case, so it's not a top priority to fix, but something nice for the backlog.

**Comment by zoepage** [comment]
It breaks here:https://github.com/gr2m/initials/blob/gh-pages/initials.js#L176
`splice` changes the array dynamically in the for-loop.

possible solution:
`possibleInitials[i] = undefined` and `possibleInitials = possibleInitials.filter(Boolean)`
breaks 13 tests.

**Comment by gr2m** [comment]
closing in favor of https://github.com/gr2m/initials/issues/14

**Comment by zoepage** [comment]
A great idea @gr2m :)
