### ISSUE TITLE
Name-SecondName doesn't get initials

### ISSUE THREAD

**Issue by zoepage** [gr2m/initials#18]
`Jan-Erik` doesn't get an initial.
Do we treat this as a bug @gr2m?

**Comment by gr2m** [comment]
Sounds like a bug, but I can't reproduce it here: http://gr2m.github.io/initials/. Can you start a PR with a failing test?

**Comment by zoepage** [comment]
Test isn't failing, so I guess this issue lies in another module.
Actually we have 2 issues here... 
1. The `-` gets deleted (initials inserted manually)
2. No initial gets parsed. 
![bildschirmfoto 2015-10-07 um 07 06 26](https://cloud.githubusercontent.com/assets/562354/10329458/1688fbea-6cc2-11e5-99c9-acb7d45f21ca.png)

So, I'll leave the issue here until I found the issue in the right layer.
