### ISSUE TITLE
Can't handle emoji in names

### ISSUE THREAD

**Issue by Froelund** [gr2m/initials#30]
Emojis ends up as an illegal character:
```
t.equal(initials('John 🐐face'), 'J🐐', 'John 🐐face (j🐐) ☛ j🐐');

✖ John 🐐face (j🐐) ☛ j🐐
    --------------------------
      operator: equal
      expected: 'J🐐'
      actual:   'J�'
      stack: |-
```

**Comment by gr2m** [comment]
that’s a new one :) How would you fix it?

**Comment by Froelund** [comment]
Yes! The times they are a-changin' 👍 
I don't know what the exact issue is, but I suspect something with number of bytes taken from the lastname doesn't match the length of the first character(emoji).

**Comment by gr2m** [comment]
So I see two ways addressing this

1. Mention in the README that initials doesn’t handle emojis well
2. Implement some good handling of emojis that I don’t see right now :)

**Comment by gr2m** [comment]
@Froelund did you come up with a workaround?
