### ISSUE TITLE
test.test@test.org <test.test@test.org>

### ISSUE THREAD

**Issue by gr2m** [gr2m/initials#7]
should become `test.test@test.org (tt) <test.test@test.org>`, but becomes ` test test test org (test.test@test.org <test.test@test.org>) <test.test@test.org> `

**Comment by zoepage** [comment]
@gr2m To make sure the schema is right:

(tt) -> test1.test2@test3.org -> (t1t2) or (t1t3)?

**Comment by gr2m** [comment]
I've added a test in https://github.com/gr2m/initials/issues/8

I'm not sure what you mean by this?
> (tt) -> test1.test2@test3.org -> (t1t2) or (t1t3)?

**Comment by zoepage** [comment]
thanks for the tests :)
just want to know which letters are inserted?

so:
1. abc.def@xyz.org (ad)
2. abc.def@xyz.org (ax)
3. abc.def@xyz.org (adx)

**Comment by gr2m** [comment]
when you only add an email, the first letters of every word before the `@` are used, so 

```
initials('abc.def@xyz.org') === 'ad'
```
