### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Fleuv** [gr2m/initials#76]
Are there any plans to add TypeScript support?

**Comment by gr2m** [comment]
no plans on my side, sorry. I don't want to rewrite initials to TypeScript, but if you'd want to submit a pull request with a `.d.ts` file then I'd be happy to review it

**Comment by mskelton** [comment]
Should this issue be closed now that declarations are in the repo?

**Comment by gr2m** [comment]
I need to release the new version first. I've to replace travis with GitHub actions to re-enable automated releases. I can do that right now hold on
