### ISSUE TITLE
More intelligent TypeScript return type

### ISSUE THREAD

**Issue by ikornienko** [gr2m/initials#81]
### Problem

Currently it has

```ts
type NameOrNames = string | string[];

function initials(nameOrNames: NameOrNames, options?: Options): string | string[];
```

which adds additional pain to the user who has to deal with the fact that

```ts
const myInitials: string = initials('John Doe');
```

won't compile, besides documentation explicitly saying that the result will be `JD` (i.e. `string`). 

### Possible way to improve typings

```ts
type NameOrNames = string | string[];

function initials<T extends NameOrNames>(nameOrNames: T, options?: Options): T;
```

In this case if array is passed as a first argument, then function returns an array. And if it's just a string then its return type also is just a string.

**Comment by gr2m** [comment]
I think a better approach would be a function type override

```ts
function initials(nameOrNames: string, options?: Options): string;
function initials(nameOrNames: string[], options?: Options): string[];
```

Not sure if that's the exact syntaxt, but I think that would work better and does not require a type parameter

**Comment by ikornienko** [comment]
Function overload would be ideal! While not being a TS expert, I wasn't aware that TS supports it, but it's indeed there ([docs](https://www.typescriptlang.org/docs/handbook/functions.html#overloads)). Definitely better to make those two function signatures defined explicitly.
