### ISSUE TITLE
BUG: wrong initials for just one word with only capital letters e.g. "JOHN"

### ISSUE THREAD

**Issue by RARgames** [gr2m/initials#85]
In this case initials are: "JOHN", I think it should be "JO" or just "J" - looking at other cases probably "JO".

The workaround is to add a space before passing into initials("JOHN ").

**Comment by gr2m** [comment]
I think you can also set your preferred initials explicitly: `JOHN (J)`

Why do you set your names in all capitals? That's not a use case that came up in the past ... decade 😅

**Comment by RARgames** [comment]
xD, not my idea. Just noticed that some people do using my app. And the style was breaking because I assumed that it is not longer than 2 letters.

**Comment by gr2m** [comment]
oh no initials are two by default, but if there is a conflict it can automatically calculate longer initials, that's why the method accepts an array, too

```js
initials(['John Doe', 'Jane Doe'])
// [ "JDo", "JaD" ]
```

I'll close the issue since there is nothing actionable to do

**Comment by gr2m** [comment]
also folks have more than one first and one last name

```js
initials('John Doodely Doe') 
// JDD
```
